INSERT INTO tb_book_list (name) VALUES ('Fiction');
INSERT INTO tb_book_list (name) VALUES ('Non-Fiction')

INSERT INTO tb_book (title, publisher, author, number_of_pages, year_of_publication, synopsis, isbn10, isbn13) VALUES ('Grande Sertão Veredas', 'Cia das Letras', 'João Guimarães Rosa', '560', '2019', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '8535931988', '978-8535931983');
INSERT INTO tb_book (title, publisher, author, number_of_pages, year_of_publication, synopsis, isbn10, isbn13) VALUES ('Odisseia', 'Penguin-Companhia', 'Homero', '576', '2011', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '8563560271', '978-8563560278');
INSERT INTO tb_book (title, publisher, author, number_of_pages, year_of_publication, synopsis, isbn10, isbn13) VALUES ('Frankstein ou o Prometeu Moderno', 'Penguin-Companhia', 'Mary Shelley', '424', '2015', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '8582850190', '978-8582850190');
INSERT INTO tb_book (title, publisher, author, number_of_pages, year_of_publication, synopsis, isbn10, isbn13) VALUES ('Economia para Transformação Social', 'Autonomia Literária', 'Pedro Rossi / Juliane Furno', '232', '2023', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '6587233945', '978-6587233949');
INSERT INTO tb_book (title, publisher, author, number_of_pages, year_of_publication, synopsis, isbn10, isbn13) VALUES ('Rápido e Devagar: Duas Formas de Pensar', 'Objetiva', 'Daniel Kahneman', '608', '2012', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '9788539003839', '978-8539003839');
INSERT INTO tb_book (title, publisher, author, number_of_pages, year_of_publication, synopsis, isbn10, isbn13) VALUES ('Hábitos Atômicos', 'Alta Life', 'James Clear', '320', '2019', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '8550807567', '978-8550807560');

INSERT INTO tb_belonging (list_id, book_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (1, 3, 2);


INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 4, 0);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 5, 1);
INSERT INTO tb_belonging (list_id, book_id, position) VALUES (2, 6, 2);
